Adding tests
ssciwr/powr-refactor pull request #12
Opened 2023-12-01 08:16 UTC by nashmit

Adding tests for [test_colitest.py](https://github.com/ssciwr/powr-refactor/blob/main/test/test_colitest.py)

2023-12-04 10:01 UTC, iulusoy commented on test/test_colitest.py
> +    colitest_file_reference = set_vars / "../test/data/colitest1.out"
for the file reference, you should add the reference data folder to the package data in the `pyproject.toml` file like [here](https://setuptools.pypa.io/en/latest/userguide/datafiles.html) or provide another fixture to set the base path. The reason for this is if we ever change the structure where powr is run, which is likely to happen in the future, then all of these tests break. So please provide a clean base path, and then we can even change the fixture that sets the path to the `powr` directory to depend on that.

2023-12-04 10:18 UTC, iulusoy commented on test/test_colitest.py
>      temp = subprocess.run(
A real problem that we do have is that the chain of subprocesses becomes detached from the original process. In principle, this is the desired behaviour, but it complicates the integration tests. There we have to be careful that all the chains of programs that are executed are terminated properly, otherwise they will interfere with the next tests.

2023-12-04 10:22 UTC, iulusoy commented on test/test_colitest.py
> +    colitest_file_reference = set_vars / "../test/data/colitest1.out"
but I guess this becomes less relevant with my proposed changes below.

2023-12-04 10:40 UTC, iulusoy commented on test/test_colitest.py
> +    # assert out1 == out2
```suggestion
    colitest_file = set_vars / "output/colitest1.out"

    with open(colitest_file, "r") as f:
        output_for_test = f.read()

    assert "Maximum Opacity at Depth 1: K= 41042;" in output_for_test
    assert "Lambda=     303.771;" in output_for_test
```

2023-12-04 10:41 UTC, iulusoy commented on test/test_colitest.py
> +    out1 = output.find("Opacities set to 0.01 * Background Opacity at    198 frequencies")
same applies here as in line 167. The reason not to search for string position but just for string matching is that the `.out` file is a log file and therefore will be different in structure.

2023-12-04 10:41 UTC, iulusoy commented on test/test_colitest.py
> +    colitest_plot_reference = set_vars / "../test/data/colitest1.plot"
for the plot file, an absolute comparison of strings is appropriate, as this is a real output file that can be further processed with a plotting utility.

2023-12-04 10:44 UTC, iulusoy commented on test/test_wrstart.py
> +    try:
see above, and this is where it gets tricky as one subprocess spawns a plethora of subprocesses that are all detached. I suggest to `sleep` in the test until you find the line `WRSTART finished` in wrstart`.log AND `WRUNIQ  finished` in wruniq1.log. We should change the input files according to Andreas' last email (adapt the threshold so it does not run so long).

2024-01-10 09:06 UTC, nashmit commented on test/test_wrstart.py
> +    try:
will do in a second PR

2024-01-15 07:58 UTC, iulusoy requested changes

2024-01-15 07:58 UTC, iulusoy commented on test/test_colitest.py
> +    # plot_np8 = extract_np_between(plot_for_test, 'N=   50   PLOTSYMBOL= 11', 'KASDEF LUN')
so at this point, we do not compare any entries that have "1D+0.3" or something similar in their header. Assuming that the numbers have been multiplied by 1.D+03, though the syntax is off. Maybe you can add one or two other tests for entries that do not have this heading, and then we have enough tests to ensure that the current status is reproduced.

2024-01-25 20:42 UTC, iulusoy approved these changes

2024-01-26 09:58 UTC, merged